from classes import Library, User
panamericana = Library(books= ["HG", "HP"])
Cristhian= User(name= "Cristhian")
Cristhian.askforBooks(panamericana)
print()
Cristhian.ask(bookSolicitude="HG", library=panamericana)
Cristhian.askforBooks(panamericana)
print()
Cristhian.returnBooks(book= "HG", library= panamericana)
Cristhian.askforBooks(panamericana)
print()
panamericana.updateBooks("100AñosDeSoledad")
print()
Cristhian.askforBooks(panamericana)
panamericana.modify(1, "poo")
print()
Cristhian.askforBooks(panamericana)
print()
panamericana.modify(1, "HG")
Cristhian.askforBooks(panamericana)